pod 'ParseUI', '~> 1.1'
pod 'ParseFacebookUtils'
pod 'Bolts', '~> 1.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'WYPopoverController', '~> 0.2.2'
pod 'DACircularProgress', '~> 2.2'
pod 'JSQMessagesViewController', '~> 7.0.1'
pod 'JSQSystemSoundPlayer', '~> 2.0.1'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'HTAutocompleteTextField'
pod 'CountryPicker'